---
-   name: Network Security Group
    azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ group.name }}-sg"
        purge_rules: yes
        rules: "{{ group.port_rules }}"
        tags: "{{ vmtags }}"
        state: "{{ state }}"
    loop: "{{ sg_groups }}"
    loop_control: 
        loop_var: group
    delegate_to: 127.0.0.1