---
-   name: Create virtual network
    azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "microblog-Vnet"
        address_prefixes: "10.0.0.0/16"
        tags: "{{ vmtags }}"



-   name: Add subnet
    azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "microblog-Subnet"
        address_prefix: "10.0.1.0/24"
        virtual_network: "microblog-Vnet"