---
instances:
    - name: appserver1
      type: appserver
    - name: appserver2
      type: appserver
    - name: database
      type: database
    - name: loadbalancer
      type: loadbalancer

relative_names:
    - name: www # www.<domain>
    - name: "@" # so <domain> works as a URL. Otherwise only www.<domain> would work.
    # - name: www.appserver1
    # - name: www.appserver2
    # - name: appserver1
    # - name: appserver2

