---
-   name: Get facts by tags
    azure_rm_virtualmachine_info:
        resource_group: "{{ resource_group }}"
    delegate_to: localhost
    register: az_facts



-   name: Display all variables/facts known for a host
    debug:
        var: az_facts



-   name: add instance to hosts
    add_host:
        name: "{{ item.tags.PublicIP }}"
        groups:
        - "{{ item.name[0:-3] }}" # instance name from provision_instances/vars/main.yml
        - "{{ item.tags.Type }}" # instance type from provision_instances/vars/main.yml
        - devops
        # the keys below are dynamic and can have any name and value. A way to add data to the host which can be read later
        iname: "{{ item.name[0:-3] }}"
        itype: "{{ item.tags.Type }}"
    with_items: "{{ az_facts.vms }}"
    when: item.tags.PublicIP is defined and item.power_state == "running"



-   name: Display all variables/facts known for a host
    debug:
        var: hostvars