docker_packages:
  - docker-ce
  - docker-ce-cli 
  - containerd.io 
  - docker-buildx-plugin 
  - docker-compose-plugin

required_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - software-properties-common