---
- name: Install Docker
  apt:
    name: docker.io
    state: latest
    update_cache: yes

- name: Install pip3
  apt:
    name: python3-pip
    state: present

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present
