---
-   name: Remove microblog container
    docker_container:
        name: microblog
        state: absent

-   name: Launch microblog container
    docker_container:
        name: "microblog"
        image: morper/microblog:latest
        #published_ports: 5000:5000
        network_mode: host
        restart: True
        env:
          SECRET_KEY: my-secret-key
          DATABASE_URL: "mysql+pymysql://microblog:{{ db_password }}@{{ groups.database[0] }}/microblog"

-   name: Copy statsd.conf
    copy:
        src: files/statsd.conf
        dest: /home/{{ server_user }}/statsd.conf
        owner: "{{ server_user }}"
        group: "{{ server_user }}"
        mode: '0644'

-   name: Remove statsd-exporter container
    docker_container:
        name: statsd-exporter
        state: absent

-   name: Run statsd-exporter container
    command: docker run -dP \
            --name statsd-exporter \
            --restart=always \
            --net=host \
            -v /home/{{ server_user }}/statsd.conf:/statsd/statsd.conf \
            prom/statsd-exporter "--statsd.mapping-config=/statsd/statsd.conf"