global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["{{ groups['monitoring'][0] }}:9100"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["{{ groups['monitoring'][0] }}:9090"]

  - job_name: "flask"
    static_configs:
      - targets:
          - "{{ groups['appserver'][2] }}:8000"
          - "{{ groups['appserver'][3] }}:8000"
        labels:
          instance: "flask"

  - job_name: "nginx"
    metrics_path: /prometheus
    static_configs:
      - targets: ["{{ groups['loadbalancer'][0] }}:9113"]
  - job_name: mysql-node
    metrics_path: /metrics
    static_configs:
      - targets: ["{{ groups['database'][0] }}:9100"]

  - job_name: "mysql-node"
    metrics_path: /metrics
    static_configs:
      - targets: ["{{ groups['database'][0] }}:9100"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "rules.yml"
