---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: northeurope
resource_group: <your resource group> # Change me
domain_name: <your domain> # Change me

admin_email: <an email>

vmtags:
    StudentId: <acronym> # Change me


pub_ssh_key_location: '<path to you local ssh public key>' # Change me, your local ssh key!


# The user Azure creates on the VMs. 10-first-minutes removes it.
root_user: azureuser

server_user: "deploy"
server_user_pass: "<a password>" # change me
server_user_groups:
    -   sudo

# Let's Encrypt only gives 5 real certificates a week for the same domain. Use true while you build and test,
# the certificate is then not trusted by browsers. Use false when everything works to get a real certificate.
certbot_staging: true
