---
root_password: $6$uSFDEpcx3$tqbQCXH5lhomwzuCkDerW3zXraQCZfMTUomQKhy47959sDZbzlT0GjwAjjVXs8dcwaUVveOoGv94lSy9R0IEQ0

server_user: deploy

server_user_password: $6$uSFDEpcx3$tqbQCXH5lhomwzuCkDerW3zXraQCZfMTUomQKhy47959sDZbzlT0GjwAjjVXs8dcwaUVveOoGv94lSy9R0IEQ0

server_user_groups:
    -   sudo

pub_ssh_key_location:
    -   ~/.ssh/azureci.pub

mysql_root_password: malte2004

mysql_database_name: microblog

mysql_user: microblog

mysql_password: malte2004

mysql_volume_path: /home/deploy/mysql-data