# syntax=docker/dockerfile:1.4

FROM python:3.8-alpine

ARG APP_VERSION=unknown
ENV APP_VERSION=${APP_VERSION}

RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . . 
COPY app app 
COPY migrations migrations 
COPY requirements requirements 
COPY requirements.txt microblog.py docker/boot.sh ./
COPY gunicorn_config.py gunicorn_config.py

# Update the package manager and install necessary dependencies
RUN apk update && \
  apk upgrade && \
  apk add --no-cache gcc musl-dev linux-headers

RUN pip install --upgrade pip setuptools


# Combine Python environment setup and dependencies installation with chmod and chown commands
RUN <<-EOF
    apk add --no-cache make && \
    apk upgrade --no-cache && \
    python -m venv .venv && \
    .venv/bin/pip3 install --no-cache-dir -r requirements.txt && \
    chmod +x boot.sh && \
    chown -R microblog:microblog ./
EOF

HEALTHCHECK --interval=60s --timeout=20s --start-period=5s --retries=3 \
  CMD curl --fail http://localhost:5000/ || exit 1

ENV prometheus_multiproc_dir /tmp

ENV FLASK_APP microblog.py

USER microblog

EXPOSE 5000 
ENTRYPOINT ["./boot.sh"]