# syntax=docker/dockerfile:1.4

FROM python:3.8-alpine
# hadolint ignore=DL3018
RUN apk add --no-cache make && \
    adduser -D microblog

WORKDIR /home/microblog

COPY requirements requirements
COPY requirements.txt pytest.ini Makefile .coveragerc .pylintrc microblog.py test.sh ./
COPY migrations migrations

RUN python -m venv .venv && \
    .venv/bin/pip3 install -r requirements/test.txt

ENV FLASK_APP microblog.py

RUN chmod +x test.sh && \
    chown -R microblog:microblog ./

USER microblog

ENTRYPOINT ["./test.sh"]

