version: "3"
services:
  db:
    platform: linux/amd64
    image: "mysql:5.7"
    restart: always
    container_name: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - db-data-mysql5:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      timeout: 5s
      retries: 10
volumes:
  db-data-mysql5: