"""followers

Revision ID: 730ce9f2fda7
Revises: 6d677d0a79a4
Create Date: 2022-11-03 15:24:31.880931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730ce9f2fda7'
down_revision = '6d677d0a79a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'followers', 'user', ['followed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_column('followers', 'followed_id')
    # ### end Alembic commands ###
