---
- name: fetch tags from GitHub API
  uri:
    url: "https://api.github.com/repos/emklemkl/microblog/tags"
    return_content: true
  register: tags_res

- name: select latest tag from response
  set_fact:
    latest_version: "{{ tags_res.json[0].name }}"

- name: debug image name
  debug:
    msg: "The image name is: eeemiiil/microblog:{{ latest_version }}-prod"

- name: latest version of dock image
  debug:
    msg: "The latest version is {{ latest_version }}"

    # name: "eeemiiil/microblog:{{ latest_version }}-prod"

- name: pull the most recent image
  docker_image:
    name: "eeemiiil/microblog:{{ latest_version }}-prod"
    source: pull
  register: pull_result

- name: Debug pull result
  debug:
    var: pull_result

- name: remove any existing microblog containers
  docker_container:
    name: appserver
    state: absent

- name: start appserver containers
  docker_container:
    name: appserver
    image: "eeemiiil/microblog:{{ latest_version }}-prod"
    env:
      VERSION: "{{ latest_version }}"
      FLASK_APP: "microblog.py"
      FLASK_ENV: "development"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "microblog"
      MYSQL_DATABASE: "microblog"
      MYSQL_ROOT_PASSWORD: "microblog"
      DB_HOST: "db"
      SECRET_KEY: "my-secret-key"
      DATABASE_URL: "mysql+pymysql://microblog:microblog@{{ groups['database'][0] }}:3306/microblog"
    volumes:
      - mysql_data:/var/lib/mysql
    state: started
    restart_policy: always
    published_ports:
      - "8000:5000"

- name: Debug the latest_version variable
  debug:
    msg: "The latest version is: {{ latest_version }}"

- name: debug the first host in the database group
  debug:
    msg: "The database host is {{ groups['database'][0] }}"

- name: check if correct image is running
  debug:
    msg: "The pulled image tag matches {{ latest_version }}"
  when: "'eeemiiil/microblog:' ~ latest_version ~ '-prod' in pull_result.image.RepoTags"

- name: check if wrong image is running
  debug:
    msg: "The pulled image tag DOES NOT match {{ latest_version }}"
  when: "'eeemiiil/microblog:' ~ latest_version ~ '-prod' not in pull_result.image.RepoTags"
