---
- name: Rolling update for Microblog Application
  hosts: appservers
  serial: 1 # Kör en server i taget
  vars:
    dockerhub_username: "beha20"
    ansible_python_interpreter: /usr/bin/python3
  remote_user: deploy
  become: yes
  become_method: sudo
  tasks:

    - name: Pull the latest Microblog image based on GitHub release tag
      docker_image:
        name: "{{ dockerhub_username }}/microblog:{{ github_release_tag }}"
        source: pull

    - name: Stop existing Microblog container
      docker_container:
        name: microblog
        state: absent

    - name: Restart Microblog Container
      docker_container:
        name: microblog
        image: "{{ dockerhub_username }}/microblog:{{ github_release_tag }}"
        env:
          DATABASE_URL: "{{ 'mysql+pymysql://' + db_username + ':' + db_password + '@' + groups.database[0] + ':' + '3306/' + db_name }}"
        ports:
          - "8000:5000"  # Ensure this maps the internal port to the correct external port
        restart_policy: always
        state: started

    - name: Wait for the application to start
      wait_for:
        port: 8000
        delay: 10 # Seconds

    - name: Verify the deployment
      uri:
        url: "http://{{ inventory_hostname }}:8000/"
        return_content: yes
        status_code: 200
      register: result
