---
- name: Blue-Green Deployment of Docker App with Docker Compose
  hosts: appservers
  remote_user: deploy
  become: true
  serial: 1  # Ensures that one server is updated at a time?
  vars:
    db_vars:
      MYSQL_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "microblog"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "my-password"
    app_env:
      SECRET_KEY: "ca9c838c110047c0ba1a7750353886b5"
      DATABASE_URL: "mysql+pymysql://microblog:my-password@13.74.186.90/microblog"
  tasks:
    - name: Check if Docker Compose is installed
      command: docker-compose --version
      register: docker_compose_installed
      failed_when: false

    - name: Install Docker Compose if not present
      when: docker_compose_installed.rc != 0
      apt:
        name: docker-compose
        state: present

    - name: Clone the repository to get the latest docker-compose.yml file
    git:
      repo: 'https://github.com/deadbacteria8/microblog.git'
      dest: /home/deploy/microblog
      version: ansible_cd
      force: yes

    - name: Copy docker-compose.yml from repo to the deployment directory
      copy:
        src: /home/deploy/microblog/ansible/roles/appserver_playbook/files/docker-compose.yml
        dest: /home/deploy/docker-compose.yml
        mode: '0644'


    - name: Run docker-compose up with environment variables
      shell: |
        docker compose pull
      args:
        chdir: /home/deploy
      environment: "{{ app_env }}"

    - name: Pull the docker img using docker-compose
      command: docker-compose pull
      args:
        chdir: /home/deploy
      environment: "{{ app_env }}"

    - name: Stop and remove the old containers
      command: docker-compose down
      args:
        chdir: /home/deploy
      ignore_errors: yes
      environment: "{{ app_env }}"

    - name: Start the new containers with Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/deploy
      environment: "{{ app_env }}"

    - name: Check if the containers are running
      command: docker-compose ps
      args:
        chdir: /home/deploy
      register: docker_compose_status
      retries: 5
      delay: 10
      until: "'Up' in docker_compose_status.stdout"
      environment: "{{ app_env }}"

    - name: Get the Docker image version
      command: docker inspect --format '{{.Config.Image}}' microblog
      register: docker_image_version
      failed_when: false

    - name: Display the Docker image version
      debug:
        msg: "The current Docker image version is {{ docker_image_version.stdout }}"