---
- name: Continuous Deployment
  hosts: production
  remote_user: deploy
  become: true

  tasks:
    - name: Remove the existing Microblog containers
      docker_container:
        name: microblog-container
        state: absent
      ignore_errors: yes

    - name: Start the new Microblog containers
      docker_container:
        name: microblog-container
        image: kristinakalinchuk/microblog:0.1.0
        env:
          DATABASE_URL: "mysql+pymysql://microblog:G5Evdo1IqgVNl51@{{ groups['databasen'][0] }}:3306/microblog"
        ports:
          - "8000:5000"
        networks:
          - name: microblog-network
        restart_policy: always
