---
- name: Continuous Deployment
  hosts: production
  remote_user: deploy
  become: true

  tasks:
    - name: Get the latest GitHub release tag
      uri:
        url: "https://api.github.com/repos/kalinchukkristina/microblog/releases/latest"
        method: GET
        return_content: yes
      register: github_release

    - name: Set the release tag as a variable
      set_fact:
        release_tag: "{{ github_release.json.tag_name | regex_replace('^v', '') }}"

    - name: Remove the existing Microblog containers
      docker_container:
        name: microblog
        state: absent
      ignore_errors: yes
    
    - name: Connect to Docker Network
      docker_network:
        name: microblog-network
        state: present
    - name: Start Microblog Container
      docker_container:
        name: microblog
        image: "kristinakalinchuk/microblog:{{ release_tag }}"
        env:
          DATABASE_URL: "mysql+pymysql://microblog:G5Evdo1IqgVNl51@{{ groups['databasen'][0] }}:3306/microblog"
        ports:
          - "8000:5000"
        networks:
          - name: microblog-network
        restart_policy: always
