---
-   
    name: CD_playbook
    hosts:
        -   appservers
    remote_user: deploy
    become: yes
    tasks:
      - name: testing stuff works
        command: ansible --version
        register: ansible_version
        changed_when: false

      - name: Pull the docker img
        docker_image:
          name: deadbacteria8/docker-prod
          tag: "1.4.0"
          source: pull

      - name: Start new docker container
        docker_container:
          name: app_new_container
          image: deadbacteria8/docker-prod:1.4.0
          state: started
          restart_policy: always
          ports:
            - "80:80"
          healthcheck:
            test ["CMD", "curl", "-f", "http://deadbacteria8.tech:80"]
            interval: 30s
            retries: 3
            start_period: 30s
            timeout: 30s

          - name: Waitin for the new container to be healthy
            docker_container:
              name: app_new_container
              state: started
            register: new_container_status
            until: new_container_status.container.health.status == 'healthy'
            retries: 10
            delay: 10

          - name: Stop and remove the old Docker container
            docker_container:
              name: app_old_container  # name of old container get later
              state: absent
            when: new_container_status.container.health.status == 'healthy'