---
-   hosts: local
    connection: local
    gather_facts: False
    collections:
        - azure.azcollection
    roles:
        - gather_instances
-   hosts: loadbalancer
    remote_user: "{{ server_user }}"
    become: yes
    become_method: sudo
    roles:
        -   loadbalancer