---
  -   hosts:
          -   loadBalancer
      remote_user: azureuser
      become: yes
      become_method: sudo
      vars:
          ansible_python_interpreter: /usr/bin/python3
      roles:
          -   setup_loadbalancer