---
-   name: Create node exporter user
    user:
        name: "{{ node_exporter_user }}"
        system: yes
        create_home: no
        state: present

-   name: Download and unarchive node exporter
    unarchive:
        src: https://github.com/prometheus/node_exporter/releases/download/{{ node_exporter_version_path }}
        dest: /home/deploy
        remote_src: yes

-   name: Copy node_exporter to directory
    copy:
        src: /home/{{ server_user }}/{{ node_exporter_dir_name }}/node_exporter
        dest: /usr/local/bin/node_exporter
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_user }}"
        mode: '0755'
        remote_src: yes

-   name: Remove temp dir
    file:
        path: /home/{{ server_user }}/{{ node_exporter_dir_name }}/
        state: absent

-   name: Copy node_exporter.service
    copy:
        src: files/node_exporter.service
        dest: /etc/systemd/system
        mode: "go-w"

-   name: Reload systemctl 
    systemd:
        daemon_reload: yes

-   name: Start and enable node_exporter
    systemd:
        state: started
        name: node_exporter
        enabled: yes
