---
- name: Set root password
  user:
      name: root
      password: "{{ root_password }}"

- name: Update apt-cache and upgrade
  apt:
      force_apt_get: yes
      update_cache: "True"
      cache_valid_time: 3600
      upgrade: yes

- name: Install packages
  apt:
      force_apt_get: yes
      name: "{{ packages }}"

- name: Copy unattended upgrades 10 settings
  copy:
      mode: "644"
      src: files/apt_periodic
      dest: /etc/apt/apt.conf.d/10periodic

- name: Copy unattended upgrades 50 settings
  copy:
      mode: "644"
      src: files/apt_periodic_50
      dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Backup existing sshd_config if it exists
  command: mv /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
  args:
    creates: /etc/ssh/sshd_config
  ignore_errors: yes

- name: Copy sshd_config file
  copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config

- name: Create user
  user:
      name: "{{ server_user }}"
      password: "{{ server_user_pass }}"
      state: present
      shell: /bin/bash
      groups: "{{ server_user_groups }}"

- name: Add all ssh-keys for new user
  authorized_key: 
      user: "{{ server_user }}"
      state: present
      key: "{{ lookup('file' , item) }}"
  with_items: "{{ all_user_shh_keys }}"

- name: Add user to sudoers
  lineinfile:
      dest: /etc/sudoers
      regexp: "{{ server_user }} ALL"
      line: "{{ server_user }} ALL=(ALL) NOPASSWD:ALL"
      state: present
      validate: "/usr/sbin/visudo -cf %s" # kan få fel med line "{{ server_user }} testing"

- name: flush handlers to restart SSH
  meta: flush_handlers # we cant do it later because after this we cant ssh as root

- name: Remove default user
  remote_user: "{{ server_user }}"
  user:
      name: azureuser
      state: absent
      force: yes
      remove: yes
  # ignore_errors: yes
