---
-   name: Launch database container
    docker_container:
        name: "mysql"
        image: mysql:5.7
        published_ports: 3306:3306
        volumes:
          - "{{ mysql_volume_path }}:/var/lib/mysql:rw"
        restart: True
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_DATABASE: "{{ mysql_database_name }}"
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_PASSWORD: "{{ mysql_password }}"
