name: Debug Release Event

on:
  release:
    types:
      - published

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print event payload
        run: echo "${{ toJson(github.event) }}"
