name: abc

on: [release]

jobs:
  call-workflow-ci:
    uses: ./.github/workflows/make_test_ci.yml
  deploy-to-dockerhub:
    needs: call-workflow-ci
    runs-on: ubuntu latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: deadbacteria8/docker-prod:1.2.0