name: Continuous Deployment

on:
  release:
    types:
      - created  # Körs när en ny release skapas

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install ansible
        ansible-galaxy install -r

    - name: Run Ansible CD playbook
      run: |
        ansible-playbook -i ansible/hosts cd_playbook.yml --limit production
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
