name: Publish Docker Images

on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["Pytest"]
    types:
      - completed
    branches:
      - master


jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract the version tag
      run: echo "VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')" >> $GITHUB_ENV
      
    - name: Build and Push Docker Image Test
      run: |
        docker build -t kristinakalinchuk/microblog-test:${{ env.VERSION }} -f docker/Dockerfile_test .
        docker push kristinakalinchuk/microblog-test:${{ env.VERSION }}

    - name: Build and Push Docker Images Prod App
      run: |
        docker build -t kristinakalinchuk/microblog:${{ env.VERSION }} -f docker/Dockerfile_prod .
        docker push kristinakalinchuk/microblog:${{ env.VERSION }}

    env:
      DOCKER_CLI_AK: true
