name: Roll out changes on Ansible hosts

on:
  release:
    types: [published]

jobs:
  publish-to-docker-hub:
    uses: ./.github/workflows/publish-to-docker-hub.yml
  roll-out-changes:
    name: Roll out versions on Ansible hosts
    runs-on: ubuntu-latest
    needs: publish-to-docker-hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install ansible -y

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ./ansible/cd_appserver.yml --skip-tags init -e "app_version=${{ github.event.release.tag_name }}"

        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
