name: Roll out changes on Ansible hosts

on:
  workflow_run:
    workflows: ["Publish Docker image"]
    types:
      - completed

jobs:
  roll-out-changes:
    name: Roll out versions on Ansible hosts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible  # Set the working directory for all steps in this job
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install ansible -y

      - name: Run Ansible Playbook
        run: |
          ansible-playbook cd_appserver.yml --skip-tags init -e "app_version=${{ github.event.release.tag_name }}"

        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"

