name: Continuous Deployment

on:
  push:
    branches: ["AnsibleContinuousDeployment"]
  pull_request:
    branches: ["AnsibleContinuousDeployment"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install ansible docker

    - name: Set up SSH
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 'appserver1.kristinadev.me' >> ~/.ssh/known_hosts
        ssh-keyscan -H 'appserver2.kristinadev.me' >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Run Ansible CD playbook
      run: |
        ansible-playbook -i ansible/hosts ansible/cd_playbook.yml --limit production -e 'ansible_ssh_common_args="-o StrictHostKeyChecking=no"'
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
