name: Rolling Update Deployment

on:
  push:
    branches:
      - "dev/beha20/kmom05"
  workflow_call:
    
jobs:
  deploy:

    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.azure_ssh }}

      - name: Install doppler
        uses: dopplerhq/cli-action@v2

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Rolling Update Playbook
        run: doppler run -- ansible-playbook -i ansible/hosts ansible/cd.yml -e "github_release_tag=dev-beha20-kmom03"
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_DEV }}