name: Publish Docker

on:
  release:
    types:
      - published

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.13"

      - name: Set up a virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Check distutils
        run: python -c "import distutils.util"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt
          sudo apt-get update && sudo apt-get install -y build-essential

      - name: Running Tests
        run: |
          make test

  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract the version tag from release
        if: ${{ github.event_name == 'release' }}
        run: echo "VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')" >> $GITHUB_ENV

      - name: Build and Push Docker Image Test
        run: |
          docker build -t kristinakalinchuk/microblog-test:${{ env.VERSION }} -f docker/Dockerfile_test .
          docker push kristinakalinchuk/microblog-test:${{ env.VERSION }}

      - name: Build and Push Docker Images Prod App
        run: |
          docker build -t kristinakalinchuk/microblog:${{ env.VERSION }} -f docker/Dockerfile_prod .
          docker push kristinakalinchuk/microblog:${{ env.VERSION }}
