name: Security Checks Workflow

on:
  push:
    branches: [ "dev/beha20/kmom03" ]
  workflow_call:
    

jobs:
  security_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make
          pip install bandit
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Install Dockle
        run: |
          VERSION=$(curl -s https://api.github.com/repos/goodwithtech/dockle/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          curl -L -o dockle.deb "https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.deb"
          sudo dpkg -i dockle.deb
          rm dockle.deb

      - name: Set Random Tag Name
        id: set_random_tag
        run: echo "::set-output name=RANDOM_TAG::$(uuidgen)"

      - name: Run Trivy
        run: make trivy-test TAG=${{ steps.set_random_tag.outputs.RANDOM_TAG }}-prod

      - name: Run Bandit
        run: make bandit-test

      - name: Run Trivy and Dockle
        run: |
          make trivy-test TAG=${{ steps.set_random_tag.outputs.RANDOM_TAG }}-prod
          make dockle-test TAG=${{ steps.set_random_tag.outputs.RANDOM_TAG }}-prod
